#!/bin/bash

# format a pdf file for brochure-style printing

PROGNAME=$(basename $0)

usage () {
    echo "$PROGNAME: Usage: $PROGNAME [options] PDF-FILE"
}

for arg ; do
    if [[ $arg =~ ^--sheets= ]] ; then
        sheets=${arg#--sheets=}
        if [[ ! $sheets =~ ^[0-9]+$ || $sheets -le 0 ]] ; then
            echo "$PROGNAME: invalid argument to option 'sheets'" >&2
            echo "  Arguments to 'sheets' must be a positive integer."
            exit 1
        fi
        shift
break  # With one option for now, let's quit while we're ahead.
    fi
done

if [ $# -ne 1 ] ; then
    usage >&2
    exit 2
fi

if [ $(dd if=$1 bs=4 count=1 2>/dev/null) != '%PDF' ] ; then
    {
        echo "$PROGNAME: input file does not appear to be in PDF format"
        usage
        echo "$PROGNAME: exiting"
    } >&2
    exit 3
fi

infile=$1
pages=$(pdfinfo -meta $infile | grep Pages: | cut -d: -f2)
pps=$(( ${sheets:=4} * 4 ))  # pages per style; 4 pages per sheet
styles=$(( pages / pps ))
(( pages % pps )) && ((++styles))


function make_sequence {
    local sequence end
    end=${1:-$pps}
    for ((i=0; i < end/2; i++)) ; do
        case $((i%2)) in
        0) sequence+=( $((end-i)) $((1+i)) ) ;;
        1) sequence+=( $((1+i)) $((end-i)) ) ;;
        esac
    done
    echo ${sequence[@]}
}

sequence=( $(make_sequence) )
len_seq=$pps
fmt_w=${#styles}  # width for zero padding in the output filenames
pdfseparate $infile page-%d.pdf
echo | groff -T pdf > blank.pdf

# ns: number of style
for ((ns=0; ns<styles; ns++)) ; do
    # po: page offset
    po=$((ns * pps))
    # todo: option for full padding
    if ((ns+1 == styles && pages%pps)) ; then
        len_seq=$((pages - po + pages%4)) 
        sequence=( $(make_sequence $len_seq) )
    fi
    for ((i=0; i<len_seq; i++)) ; do
        page_no=$((po + ${sequence[i]}))
        if (($page_no <= $pages)) ; then
            page=page-${page_no}.pdf 
            style[$i]=$page 
        else
            style[$i]=blank.pdf
        fi
    done
    pdfunite ${style[@]} style-$(printf "%0${fmt_w}d" $ns).pdf
    rm $(grep -o 'page[^ ]*' <<< ${style[@]})
    unset style
done

rm blank.pdf
